name: Terraform Plan

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: '.'

      - name: Setup Terraform
        uses: hashicorp/terraform-github-actions@v2.0.0
        with:
          terraform_version: '1.1.9'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Aprovação manual
        uses: actions/manual-approval@v1
        with:
          approver: ${{ github.actor }}

      - name: Terraform Apply
        run: terraform apply